# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 11:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(blank=True, null=True)),
                ('period', models.IntegerField(choices=[(1, 1), (2, 2), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)])),
                ('cart', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('LAB', 'LAB')], max_length=4)),
                ('is_reserved', models.BooleanField(default=False)),
                ('recurrences', recurrence.fields.RecurrenceField()),
                ('teacher', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
