# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20170731_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.DateField(),
        ),
    ]
