# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-15 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20170731_1304'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('day', 'period', 'cart')]),
        ),
    ]
